package service

import mock "github.com/stretchr/testify/mock"

// MockKindInterface is an autogenerated mock type for the KindInterface type
type MockKindInterface struct {
	mock.Mock
}

// ApplyKind provides a mock function with given fields: kubernetesNamespace, fileLines, namespaceWithoutPrefix
func (_m *MockKindInterface) ApplyKind(kubernetesNamespace string, fileLines []string, namespaceWithoutPrefix string) error {
	ret := _m.Called(kubernetesNamespace, fileLines, namespaceWithoutPrefix)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, string) error); ok {
		r0 = rf(kubernetesNamespace, fileLines, namespaceWithoutPrefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CleanupKind provides a mock function with given fields: kubernetesNamespace
func (_m *MockKindInterface) CleanupKind(kubernetesNamespace string) error {
	ret := _m.Called(kubernetesNamespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(kubernetesNamespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
