package mocks

import "k8s.io/client-go/kubernetes"
import "github.com/stretchr/testify/mock"

// BuilderInterface is an autogenerated mock type for the BuilderInterface type
type BuilderInterface struct {
	mock.Mock
}

// GetClientSet provides a mock function with given fields: projectID, zone, clusterId
func (_m *BuilderInterface) GetClientSet(projectID string, zone string, clusterId string) (kubernetes.Interface, error) {
	ret := _m.Called(projectID, zone, clusterId)

	var r0 kubernetes.Interface
	if rf, ok := ret.Get(0).(func(string, string, string) kubernetes.Interface); ok {
		r0 = rf(projectID, zone, clusterId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(projectID, zone, clusterId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
