package _mocks

import mock "github.com/stretchr/testify/mock"

// ApplicationServiceInterface is an autogenerated mock type for the ApplicationServiceInterface type
type ApplicationServiceInterface struct {
	mock.Mock
}

// CreateForNamespace provides a mock function with given fields:
func (_m *ApplicationServiceInterface) CreateForNamespace() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByNamespace provides a mock function with given fields:
func (_m *ApplicationServiceInterface) DeleteByNamespace() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasNamespace provides a mock function with given fields:
func (_m *ApplicationServiceInterface) HasNamespace() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UpdateByNamespace provides a mock function with given fields:
func (_m *ApplicationServiceInterface) UpdateByNamespace() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
