package _mocks

import loader "kube-helper/loader"
import mock "github.com/stretchr/testify/mock"

// BranchLoaderInterface is an autogenerated mock type for the BranchLoaderInterface type
type BranchLoaderInterface struct {
	mock.Mock
}

// LoadBranches provides a mock function with given fields: bitbucket
func (_m *BranchLoaderInterface) LoadBranches(bitbucket loader.Bitbucket) ([]string, error) {
	ret := _m.Called(bitbucket)

	var r0 []string
	if rf, ok := ret.Get(0).(func(loader.Bitbucket) []string); ok {
		r0 = rf(bitbucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(loader.Bitbucket) error); ok {
		r1 = rf(bitbucket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
