package _mocks

import "kube-helper/loader"
import "github.com/stretchr/testify/mock"

// ConfigLoaderInterface is an autogenerated mock type for the ConfigLoaderInterface type
type ConfigLoaderInterface struct {
	mock.Mock
}

// LoadConfigFromPath provides a mock function with given fields: filepath
func (_m *ConfigLoaderInterface) LoadConfigFromPath(filepath string) (loader.Config, error) {
	ret := _m.Called(filepath)

	var r0 loader.Config
	if rf, ok := ret.Get(0).(func(string) loader.Config); ok {
		r0 = rf(filepath)
	} else {
		r0 = ret.Get(0).(loader.Config)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filepath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
